// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARntA7Ff2mXXlTrZfB8YEC-ASTGiiNujI',
    appId: '1:301847550887:web:747a4722b209cf4e203482',
    messagingSenderId: '301847550887',
    projectId: 'project-1126612155927744763',
    authDomain: 'project-1126612155927744763.firebaseapp.com',
    databaseURL: 'https://project-1126612155927744763.firebaseio.com',
    storageBucket: 'project-1126612155927744763.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtCgaXC3Gz6klnt09rKM10lEA6fLi30RY',
    appId: '1:301847550887:android:c7c8f30a5c3aedd4',
    messagingSenderId: '301847550887',
    projectId: 'project-1126612155927744763',
    databaseURL: 'https://project-1126612155927744763.firebaseio.com',
    storageBucket: 'project-1126612155927744763.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPg5RQ5qmXX54Gjfj8_v-U6fjKYmwAP48',
    appId: '1:301847550887:ios:2f82c5738f9ba70f203482',
    messagingSenderId: '301847550887',
    projectId: 'project-1126612155927744763',
    databaseURL: 'https://project-1126612155927744763.firebaseio.com',
    storageBucket: 'project-1126612155927744763.appspot.com',
    androidClientId: '301847550887-6usd2e2a0mdq5d4okf8uvlpj9cb013lm.apps.googleusercontent.com',
    iosClientId: '301847550887-vb1ej313cga4rbppv28hraao4th1jlo6.apps.googleusercontent.com',
    iosBundleId: 'com.cantadas.renid.cantadas.appPhrases',
  );
}
